import type { Metadata } from "next";
import { TopMenu } from "@/components";
import "./globals.css";
import { inter } from "@/configs/fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopMenu />
        <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
