export const products = [
  {
    productId: 1,
    imageURL: "1.jpeg",
    productURL: "1",
    productName: "Zapato Primavera Floral",
    productPrice: 70.0,
  },
  {
    productId: 2,
    imageURL: "2.jpeg",
    productURL: "2",
    productName: "Sandalia de Flores",
    productPrice: 70.0,
  },
  {
    productId: 3,
    imageURL: "3.jpeg",
    productURL: "3",
    productName: "Zandalias sencillas estilo invernal",
    productPrice: 70.0,
  },
  {
    productId: 4,
    imageURL: "4.jpeg",
    productURL: "4",
    productName: "Mocasín Floral",
    productPrice: 70.0,
  },
  {
    productId: 5,
    imageURL: "5.jpeg",
    productURL: "5",
    productName: "Zapato Casual Primavera",
    productPrice: 70.0,
  },
  {
    productId: 6,
    imageURL: "6.jpeg",
    productURL: "6",
    productName: "Zapato Deportivo con Motivos Florales",
    productPrice: 70.0,
  },
  {
    productId: 7,
    imageURL: "7.jpeg",
    productURL: "7",
    productName: "Bailarina Primaveral con Flores",
    productPrice: 70.0,
  },
  {
    productId: 8,
    imageURL: "8.jpeg",
    productURL: "8",
    productName: "Sandalia de Primavera",
    productPrice: 70.0,
  },
  {
    productId: 9,
    imageURL: "9.jpeg",
    productURL: "9",
    productName: "Zapato Elegante con Detalles Florales",
    productPrice: 70.0,
  },
  {
    productId: 10,
    imageURL: "10.jpeg",
    productURL: "10",
    productName: "Zapatilla Floral Casual",
    productPrice: 70.0,
  },
  {
    productId: 11,
    imageURL: "11.jpeg",
    productURL: "11",
    productName: "Zapato de Tacón con Motivos de Primavera",
    productPrice: 70.0,
  },
  {
    productId: 12,
    imageURL: "12.jpeg",
    productURL: "12",
    productName: "Zapato de Verano con Flores",
    productPrice: 70.0,
  },
  {
    productId: 13,
    imageURL: "13.jpeg",
    productURL: "13",
    productName: "Zapato de Playa con Estampado Floral",
    productPrice: 70.0,
  },
  {
    productId: 14,
    imageURL: "14.jpeg",
    productURL: "14",
    productName: "Zapato Primavera de Color Vivo",
    productPrice: 70.0,
  },
  {
    productId: 15,
    imageURL: "15.jpeg",
    productURL: "15",
    productName: "Zapato de Primavera con Lazos Florales",
    productPrice: 70.0,
  },
  {
    productId: 16,
    imageURL: "16.jpeg",
    productURL: "16",
    productName: "Sandalia Primaveral con Tiras Florales",
    productPrice: 70.0,
  },
  {
    productId: 17,
    imageURL: "17.jpeg",
    productURL: "17",
    productName: "Zapato de Fiesta con Motivos Florales",
    productPrice: 70.0,
  },
  {
    productId: 18,
    imageURL: "18.jpeg",
    productURL: "18",
    productName: "Zapato de Tela con Estampado Primaveral",
    productPrice: 70.0,
  },
  {
    productId: 19,
    imageURL: "19.jpeg",
    productURL: "19",
    productName: "Zapato de Piel con Detalles de Primavera",
    productPrice: 70.0,
  },
  {
    productId: 20,
    imageURL: "20.jpeg",
    productURL: "20",
    productName: "Zapato de Plataforma Floral",
    productPrice: 70.0,
  },
];
